var namespacewrappers =
[
    [ "helper", null, [
      [ "vs", null, [
        [ "DocumentImpl", "classwrappers_1_1helper_1_1vs_1_1_document_impl.html", "classwrappers_1_1helper_1_1vs_1_1_document_impl" ],
        [ "ProjectImpl", "classwrappers_1_1helper_1_1vs_1_1_project_impl.html", "classwrappers_1_1helper_1_1vs_1_1_project_impl" ],
        [ "PropertySheetSearcher", "classwrappers_1_1helper_1_1vs_1_1_property_sheet_searcher.html", "classwrappers_1_1helper_1_1vs_1_1_property_sheet_searcher" ],
        [ "SolutionImpl", "classwrappers_1_1helper_1_1vs_1_1_solution_impl.html", null ]
      ] ],
      [ "IDocument", "classwrappers_1_1helper_1_1_i_document.html", null ],
      [ "ImplPtr", "classwrappers_1_1helper_1_1_impl_ptr.html", null ],
      [ "IProject", "classwrappers_1_1helper_1_1_i_project.html", null ],
      [ "ISolution", "classwrappers_1_1helper_1_1_i_solution.html", null ],
      [ "Proxy", "classwrappers_1_1helper_1_1_proxy.html", null ],
      [ "Proxy< wrappers::vs::Document >", "classwrappers_1_1helper_1_1_proxy_3_01wrappers_1_1vs_1_1_document_01_4.html", null ],
      [ "Proxy< wrappers::vs::Project >", "classwrappers_1_1helper_1_1_proxy_3_01wrappers_1_1vs_1_1_project_01_4.html", null ],
      [ "Proxy< wrappers::vs::Solution >", "classwrappers_1_1helper_1_1_proxy_3_01wrappers_1_1vs_1_1_solution_01_4.html", null ]
    ] ],
    [ "vs", null, [
      [ "selection", null, [
        [ "Cursor", "classwrappers_1_1vs_1_1selection_1_1_cursor.html", "classwrappers_1_1vs_1_1selection_1_1_cursor" ],
        [ "Line", "classwrappers_1_1vs_1_1selection_1_1_line.html", "classwrappers_1_1vs_1_1selection_1_1_line" ],
        [ "Lines", "classwrappers_1_1vs_1_1selection_1_1_lines.html", "classwrappers_1_1vs_1_1selection_1_1_lines" ]
      ] ],
      [ "service", null, [
        [ "MakeProxy", "classwrappers_1_1vs_1_1service_1_1_make_proxy.html", "classwrappers_1_1vs_1_1service_1_1_make_proxy" ]
      ] ],
      [ "AddIn", "classwrappers_1_1vs_1_1_add_in.html", "classwrappers_1_1vs_1_1_add_in" ],
      [ "AddIns", "classwrappers_1_1vs_1_1_add_ins.html", "classwrappers_1_1vs_1_1_add_ins" ],
      [ "Base", "classwrappers_1_1vs_1_1_base.html", "classwrappers_1_1vs_1_1_base" ],
      [ "BuildEvents", "classwrappers_1_1vs_1_1_build_events.html", null ],
      [ "Collection", "classwrappers_1_1vs_1_1_collection.html", "classwrappers_1_1vs_1_1_collection" ],
      [ "Command", "classwrappers_1_1vs_1_1_command.html", "classwrappers_1_1vs_1_1_command" ],
      [ "CommandBar", "classwrappers_1_1vs_1_1_command_bar.html", "classwrappers_1_1vs_1_1_command_bar" ],
      [ "CommandBarControl", "classwrappers_1_1vs_1_1_command_bar_control.html", null ],
      [ "CommandBarControls", "classwrappers_1_1vs_1_1_command_bar_controls.html", "classwrappers_1_1vs_1_1_command_bar_controls" ],
      [ "CommandBarPopup", "classwrappers_1_1vs_1_1_command_bar_popup.html", "classwrappers_1_1vs_1_1_command_bar_popup" ],
      [ "CommandBars", "classwrappers_1_1vs_1_1_command_bars.html", "classwrappers_1_1vs_1_1_command_bars" ],
      [ "Commands", "classwrappers_1_1vs_1_1_commands.html", "classwrappers_1_1vs_1_1_commands" ],
      [ "Configuration", "classwrappers_1_1vs_1_1_configuration.html", "classwrappers_1_1vs_1_1_configuration" ],
      [ "Configurations", "classwrappers_1_1vs_1_1_configurations.html", "classwrappers_1_1vs_1_1_configurations" ],
      [ "Document", "classwrappers_1_1vs_1_1_document.html", "classwrappers_1_1vs_1_1_document" ],
      [ "Documents", "classwrappers_1_1vs_1_1_documents.html", "classwrappers_1_1vs_1_1_documents" ],
      [ "DTE", "classwrappers_1_1vs_1_1_d_t_e.html", "classwrappers_1_1vs_1_1_d_t_e" ],
      [ "Events", "classwrappers_1_1vs_1_1_events.html", "classwrappers_1_1vs_1_1_events" ],
      [ "IProjects", "classwrappers_1_1vs_1_1_i_projects.html", "classwrappers_1_1vs_1_1_i_projects" ],
      [ "IPropertySheet", "classwrappers_1_1vs_1_1_i_property_sheet.html", "classwrappers_1_1vs_1_1_i_property_sheet" ],
      [ "IPropertySheets", "classwrappers_1_1vs_1_1_i_property_sheets.html", "classwrappers_1_1vs_1_1_i_property_sheets" ],
      [ "OutputWindow", "classwrappers_1_1vs_1_1_output_window.html", "classwrappers_1_1vs_1_1_output_window" ],
      [ "OutputWindowPane", "classwrappers_1_1vs_1_1_output_window_pane.html", "classwrappers_1_1vs_1_1_output_window_pane" ],
      [ "OutputWindowPanes", "classwrappers_1_1vs_1_1_output_window_panes.html", "classwrappers_1_1vs_1_1_output_window_panes" ],
      [ "Project", "classwrappers_1_1vs_1_1_project.html", "classwrappers_1_1vs_1_1_project" ],
      [ "Projects", "classwrappers_1_1vs_1_1_projects.html", "classwrappers_1_1vs_1_1_projects" ],
      [ "ProjectsFolderImpl", "classwrappers_1_1vs_1_1_projects_folder_impl.html", "classwrappers_1_1vs_1_1_projects_folder_impl" ],
      [ "ProjectsSolutionImpl", "classwrappers_1_1vs_1_1_projects_solution_impl.html", "classwrappers_1_1vs_1_1_projects_solution_impl" ],
      [ "PropertySheet", "classwrappers_1_1vs_1_1_property_sheet.html", "classwrappers_1_1vs_1_1_property_sheet" ],
      [ "PropertySheet2012", "classwrappers_1_1vs_1_1_property_sheet2012.html", "classwrappers_1_1vs_1_1_property_sheet2012" ],
      [ "PropertySheets", "classwrappers_1_1vs_1_1_property_sheets.html", "classwrappers_1_1vs_1_1_property_sheets" ],
      [ "PropertySheets2012", "classwrappers_1_1vs_1_1_property_sheets2012.html", "classwrappers_1_1vs_1_1_property_sheets2012" ],
      [ "Solution", "classwrappers_1_1vs_1_1_solution.html", "classwrappers_1_1vs_1_1_solution" ],
      [ "SolutionEvents", "classwrappers_1_1vs_1_1_solution_events.html", null ],
      [ "SolutionFolder", "classwrappers_1_1vs_1_1_solution_folder.html", null ],
      [ "SolutionFolderHelper", "classwrappers_1_1vs_1_1_solution_folder_helper.html", "classwrappers_1_1vs_1_1_solution_folder_helper" ],
      [ "SolutionFolders", "classwrappers_1_1vs_1_1_solution_folders.html", "classwrappers_1_1vs_1_1_solution_folders" ],
      [ "StatusBar", "classwrappers_1_1vs_1_1_status_bar.html", "classwrappers_1_1vs_1_1_status_bar" ],
      [ "Subscriber", "classwrappers_1_1vs_1_1_subscriber.html", "classwrappers_1_1vs_1_1_subscriber" ],
      [ "TextSelection", "classwrappers_1_1vs_1_1_text_selection.html", "classwrappers_1_1vs_1_1_text_selection" ],
      [ "ToolWindows", "classwrappers_1_1vs_1_1_tool_windows.html", "classwrappers_1_1vs_1_1_tool_windows" ],
      [ "VCCollection", "classwrappers_1_1vs_1_1_v_c_collection.html", "classwrappers_1_1vs_1_1_v_c_collection" ],
      [ "VCFile", "classwrappers_1_1vs_1_1_v_c_file.html", null ],
      [ "VCFiles", "classwrappers_1_1vs_1_1_v_c_files.html", "classwrappers_1_1vs_1_1_v_c_files" ],
      [ "VCFilter", "classwrappers_1_1vs_1_1_v_c_filter.html", null ],
      [ "VCFilterFiles", "classwrappers_1_1vs_1_1_v_c_filter_files.html", "classwrappers_1_1vs_1_1_v_c_filter_files" ],
      [ "VCFilterFilters", "classwrappers_1_1vs_1_1_v_c_filter_filters.html", null ],
      [ "VCFilters", "classwrappers_1_1vs_1_1_v_c_filters.html", "classwrappers_1_1vs_1_1_v_c_filters" ],
      [ "VCProjectFiles", "classwrappers_1_1vs_1_1_v_c_project_files.html", "classwrappers_1_1vs_1_1_v_c_project_files" ],
      [ "VCProjectFilters", "classwrappers_1_1vs_1_1_v_c_project_filters.html", null ],
      [ "Window", "classwrappers_1_1vs_1_1_window.html", "classwrappers_1_1vs_1_1_window" ],
      [ "Windows", "classwrappers_1_1vs_1_1_windows.html", null ]
    ] ]
];