var searchData=
[
  ['saveprojectfilesasutf8',['SaveProjectFilesAsUtf8',['../a38324.html',1,'core::useful_commands::vs::misc']]],
  ['search',['Search',['../a37776.html',1,'model']]],
  ['searchingithubselectedtext',['SearchInGithubSelectedText',['../a38328.html',1,'core::useful_commands::vs::misc']]],
  ['searchingoogleselectedtext',['SearchInGoogleSelectedText',['../a38332.html',1,'core::useful_commands::vs::misc']]],
  ['searchselectedtext',['SearchSelectedText',['../a38336.html',1,'core::useful_commands::vs::misc']]],
  ['selectedtext',['SelectedText',['../a38436.html',1,'core::useful_commands::vs::tags']]],
  ['selectionevents',['SelectionEvents',['../a39656.html',1,'wrappers::vs']]],
  ['service',['Service',['../a37060.html',1,'']]],
  ['serviceprovider',['ServiceProvider',['../a39748.html',1,'wrappers::vs']]],
  ['solution',['Solution',['../a38440.html',1,'core::useful_commands::vs::tags::Solution'],['../a40032.html',1,'wrappers::vs::Solution']]],
  ['solutiondevelopmentinfo',['SolutionDevelopmentInfo',['../a39084.html',1,'core::utilities']]],
  ['solutionevents',['SolutionEvents',['../a39660.html',1,'wrappers::vs']]],
  ['solutionfolder',['SolutionFolder',['../a39888.html',1,'wrappers::vs']]],
  ['solutionfolderhelper',['SolutionFolderHelper',['../a39368.html',1,'wrappers::vs']]],
  ['solutionfolders',['SolutionFolders',['../a39900.html',1,'wrappers::vs']]],
  ['solutionhistorypage',['SolutionHistoryPage',['../a37360.html',1,'support']]],
  ['solutionimpl',['SolutionImpl',['../a39192.html',1,'wrappers::helper::vs']]],
  ['solutionproject',['SolutionProject',['../a38444.html',1,'core::useful_commands::vs::tags']]],
  ['solutiontaskspage',['SolutionTasksPage',['../a37372.html',1,'support']]],
  ['standart',['Standart',['../a38800.html',1,'core::utilities::execute::CppCheck']]],
  ['statusbar',['StatusBar',['../a39752.html',1,'wrappers::vs']]],
  ['subscriber',['Subscriber',['../a39664.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fbuildevents_20_3e',['Subscriber&lt; EnvDTE::_BuildEvents &gt;',['../a39664.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fdteevents_20_3e',['Subscriber&lt; EnvDTE::_DTEEvents &gt;',['../a39664.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fselectionevents_20_3e',['Subscriber&lt; EnvDTE::_SelectionEvents &gt;',['../a39664.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fsolutionevents_20_3e',['Subscriber&lt; EnvDTE::_SolutionEvents &gt;',['../a39664.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5ftexteditorevents_20_3e',['Subscriber&lt; EnvDTE::_TextEditorEvents &gt;',['../a39664.html',1,'wrappers::vs']]],
  ['svn',['Svn',['../a38844.html',1,'core::utilities::execute']]],
  ['svninfo',['SvnInfo',['../a38856.html',1,'core::utilities::execute']]]
];
