var searchData=
[
  ['saveprojectfilesasutf8_0',['SaveProjectFilesAsUtf8',['../a43392.html',1,'core::useful_commands::vs::misc']]],
  ['search_1',['Search',['../a42860.html',1,'model']]],
  ['searchingithubselectedtext_2',['SearchInGithubSelectedText',['../a43396.html',1,'core::useful_commands::vs::misc']]],
  ['searchingoogleselectedtext_3',['SearchInGoogleSelectedText',['../a43400.html',1,'core::useful_commands::vs::misc']]],
  ['searchinstackoverflowselectedtext_4',['SearchInStackoverflowSelectedText',['../a43404.html',1,'core::useful_commands::vs::misc']]],
  ['searchselectedtext_5',['SearchSelectedText',['../a43408.html',1,'core::useful_commands::vs::misc']]],
  ['selectedtext_6',['SelectedText',['../a43516.html',1,'core::useful_commands::vs::tags']]],
  ['selectionevents_7',['SelectionEvents',['../a44684.html',1,'wrappers::vs']]],
  ['service_8',['Service',['../a42148.html',1,'']]],
  ['serviceprovider_9',['ServiceProvider',['../a44776.html',1,'wrappers::vs']]],
  ['solution_10',['Solution',['../a43520.html',1,'core::useful_commands::vs::tags::Solution'],['../a45060.html',1,'wrappers::vs::Solution']]],
  ['solutiondevelopmentinfo_11',['SolutionDevelopmentInfo',['../a44136.html',1,'core::utilities']]],
  ['solutionevents_12',['SolutionEvents',['../a44688.html',1,'wrappers::vs']]],
  ['solutionfolder_13',['SolutionFolder',['../a44916.html',1,'wrappers::vs']]],
  ['solutionfolderhelper_14',['SolutionFolderHelper',['../a44396.html',1,'wrappers::vs']]],
  ['solutionfolders_15',['SolutionFolders',['../a44928.html',1,'wrappers::vs']]],
  ['solutionhistorypage_16',['SolutionHistoryPage',['../a42448.html',1,'support']]],
  ['solutionimpl_17',['SolutionImpl',['../a44220.html',1,'wrappers::helper::vs']]],
  ['solutionproject_18',['SolutionProject',['../a43524.html',1,'core::useful_commands::vs::tags']]],
  ['solutiontaskspage_19',['SolutionTasksPage',['../a42460.html',1,'support']]],
  ['standart_20',['Standart',['../a43860.html',1,'core::utilities::execute::CppCheck']]],
  ['statusbar_21',['StatusBar',['../a44780.html',1,'wrappers::vs']]],
  ['subscriber_22',['Subscriber',['../a44692.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fbuildevents_20_3e_23',['Subscriber&lt; EnvDTE::_BuildEvents &gt;',['../a44692.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fdteevents_20_3e_24',['Subscriber&lt; EnvDTE::_DTEEvents &gt;',['../a44692.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fselectionevents_20_3e_25',['Subscriber&lt; EnvDTE::_SelectionEvents &gt;',['../a44692.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fsolutionevents_20_3e_26',['Subscriber&lt; EnvDTE::_SolutionEvents &gt;',['../a44692.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5ftexteditorevents_20_3e_27',['Subscriber&lt; EnvDTE::_TextEditorEvents &gt;',['../a44692.html',1,'wrappers::vs']]],
  ['svn_28',['Svn',['../a43904.html',1,'core::utilities::execute']]]
];
