var searchData=
[
  ['saveprojectfilesasutf8',['SaveProjectFilesAsUtf8',['../a38160.html',1,'core::useful_commands::vs::misc']]],
  ['search',['Search',['../a37628.html',1,'model']]],
  ['searchingithubselectedtext',['SearchInGithubSelectedText',['../a38164.html',1,'core::useful_commands::vs::misc']]],
  ['searchingoogleselectedtext',['SearchInGoogleSelectedText',['../a38168.html',1,'core::useful_commands::vs::misc']]],
  ['searchinstackoverflowselectedtext',['SearchInStackoverflowSelectedText',['../a38172.html',1,'core::useful_commands::vs::misc']]],
  ['searchselectedtext',['SearchSelectedText',['../a38176.html',1,'core::useful_commands::vs::misc']]],
  ['selectedtext',['SelectedText',['../a38284.html',1,'core::useful_commands::vs::tags']]],
  ['selectionevents',['SelectionEvents',['../a39452.html',1,'wrappers::vs']]],
  ['service',['Service',['../a36916.html',1,'']]],
  ['serviceprovider',['ServiceProvider',['../a39544.html',1,'wrappers::vs']]],
  ['solution',['Solution',['../a39828.html',1,'wrappers::vs::Solution'],['../a38288.html',1,'core::useful_commands::vs::tags::Solution']]],
  ['solutiondevelopmentinfo',['SolutionDevelopmentInfo',['../a38904.html',1,'core::utilities']]],
  ['solutionevents',['SolutionEvents',['../a39456.html',1,'wrappers::vs']]],
  ['solutionfolder',['SolutionFolder',['../a39684.html',1,'wrappers::vs']]],
  ['solutionfolderhelper',['SolutionFolderHelper',['../a39164.html',1,'wrappers::vs']]],
  ['solutionfolders',['SolutionFolders',['../a39696.html',1,'wrappers::vs']]],
  ['solutionhistorypage',['SolutionHistoryPage',['../a37216.html',1,'support']]],
  ['solutionimpl',['SolutionImpl',['../a38988.html',1,'wrappers::helper::vs']]],
  ['solutionproject',['SolutionProject',['../a38292.html',1,'core::useful_commands::vs::tags']]],
  ['solutiontaskspage',['SolutionTasksPage',['../a37228.html',1,'support']]],
  ['standart',['Standart',['../a38628.html',1,'core::utilities::execute::CppCheck']]],
  ['statusbar',['StatusBar',['../a39548.html',1,'wrappers::vs']]],
  ['subscriber',['Subscriber',['../a39460.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fbuildevents_20_3e',['Subscriber&lt; EnvDTE::_BuildEvents &gt;',['../a39460.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fdteevents_20_3e',['Subscriber&lt; EnvDTE::_DTEEvents &gt;',['../a39460.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fselectionevents_20_3e',['Subscriber&lt; EnvDTE::_SelectionEvents &gt;',['../a39460.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5fsolutionevents_20_3e',['Subscriber&lt; EnvDTE::_SolutionEvents &gt;',['../a39460.html',1,'wrappers::vs']]],
  ['subscriber_3c_20envdte_3a_3a_5ftexteditorevents_20_3e',['Subscriber&lt; EnvDTE::_TextEditorEvents &gt;',['../a39460.html',1,'wrappers::vs']]],
  ['svn',['Svn',['../a38672.html',1,'core::utilities::execute']]]
];
